### ISSUE TITLE
Crashes after pattern is placed in Pattern Maker.

### ISSUE THREAD

**Issue by Shade-Jonezy** [tiffit/Defier#3]
As is stated in the title when trying to make a pattern, even in the most current version of the mod, the game crashes upon placing a pattern in.  You don't even get to place an item in to make a pattern for that item.  The concept of this mod makes it high on my list of item replication mods over any other out there.  This mod is the best at a sci-fi take over a certain other mod I know of and this mod has all it's pieces straight out of the box. 

[crash-2018-06-17_16.52.24-client.txt](https://github.com/tiffit/Defier/files/2109512/crash-2018-06-17_16.52.24-client.txt)

**Comment by tiffit** [comment]
Was unable to produce the crash, so I am guessing a coremod is causing the crash. Will look into it more.

**Comment by tiffit** [comment]
After some more testing, it looks something changed in a newer forge update. Fix coming soon.
