### ISSUE TITLE
Another Issue has arisen, sorry...

### ISSUE THREAD

**Issue by Shade-Jonezy** [tiffit/Defier#6]
Upon completing the compressor's requirement of power and items to create the "Defier Core" the world crashes, not Minecraft itself, and becomes unloadable.

**Comment by Shade-Jonezy** [comment]
Don't worry about fixing it so soon alright we all have lives outside of games and modding okay.  I appreciate all the hard work you do for the Minecraft Community.  Take care and have a great night.

**Comment by tiffit** [comment]
I am unable to reproduce this issue. Can you go into more detail into what happens and send the logs?

**Comment by Shade-Jonezy** [comment]
It appears to be working with a change of world for some reason and all I did was change the amount the Massive Star counted as.  Doubt that had anything to do with it though, but thanks for looking into it anyways.
